"""Add preferred tenure to business

Revision ID: 1c4e83cab883
Revises: 4a70a2535890
Create Date: 2026-06-24 15:52:12.866888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4e83cab883'
down_revision: Union[str, Sequence[str], None] = '4a70a2535890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('preferred_tenure_min', sa.Integer(), nullable=True))
    op.add_column('business_profiles', sa.Column('preferred_tenure_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'preferred_tenure_max')
    op.drop_column('business_profiles', 'preferred_tenure_min')
    # ### end Alembic commands ###
