"""add withdrawn status

Revision ID: 3dda4c053c43
Revises: bd3ad2f517dd
Create Date: 2026-06-24 03:01:42.350174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dda4c053c43'
down_revision: Union[str, Sequence[str], None] = 'bd3ad2f517dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'WITHDRAWN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
