"""Update bank profile fields

Revision ID: 4a70a2535890
Revises: 5d522f704bff
Create Date: 2026-06-24 12:50:49.518888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a70a2535890'
down_revision: Union[str, Sequence[str], None] = '5d522f704bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_profiles', sa.Column('min_loan_tenor', sa.Integer(), nullable=True))
    op.add_column('bank_profiles', sa.Column('max_loan_tenor', sa.Integer(), nullable=True))
    op.drop_column('bank_profiles', 'country')
    op.drop_column('bank_requirements', 'min_readiness_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_requirements', sa.Column('min_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bank_profiles', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bank_profiles', 'max_loan_tenor')
    op.drop_column('bank_profiles', 'min_loan_tenor')
    # ### end Alembic commands ###
