"""Add ai_report column

Revision ID: 5d522f704bff
Revises: 3dda4c053c43
Create Date: 2026-06-24 03:19:42.857394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d522f704bff'
down_revision: Union[str, Sequence[str], None] = '3dda4c053c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('ai_report', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'ai_report')
    # ### end Alembic commands ###
