"""Add recommendation to Match

Revision ID: bd3ad2f517dd
Revises: c42770df36fa
Create Date: 2026-06-24 01:43:50.017260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3ad2f517dd'
down_revision: Union[str, Sequence[str], None] = 'c42770df36fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('recommendation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'recommendation')
    # ### end Alembic commands ###
