"""Update match model

Revision ID: c42770df36fa
Revises: b034222386b0
Create Date: 2026-06-24 01:40:09.180744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42770df36fa'
down_revision: Union[str, Sequence[str], None] = 'b034222386b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('business_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('compatibility_score', sa.Float(), nullable=False))
    op.add_column('matches', sa.Column('passed_rules', sa.JSON(), nullable=True))
    op.add_column('matches', sa.Column('failed_rules', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('matches_application_id_fkey'), 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'business_profiles', ['business_id'], ['id'])
    op.drop_column('matches', 'application_id')
    op.drop_column('matches', 'match_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(op.f('matches_application_id_fkey'), 'matches', 'applications', ['application_id'], ['id'])
    op.drop_column('matches', 'failed_rules')
    op.drop_column('matches', 'passed_rules')
    op.drop_column('matches', 'compatibility_score')
    op.drop_column('matches', 'business_id')
    # ### end Alembic commands ###
