"""Add document verification system

Revision ID: d6a656e6c91a
Revises: 1c4e83cab883
Create Date: 2026-06-24 19:34:55.987640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a656e6c91a'
down_revision: Union[str, Sequence[str], None] = '1c4e83cab883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.dialects import postgresql
    
    op.execute("CREATE TYPE documenttype AS ENUM ('GST_CERTIFICATE', 'PAN_CARD', 'INCOME_TAX_RETURN', 'BANK_STATEMENT')")
    op.execute("CREATE TYPE documentstatus AS ENUM ('UPLOADED', 'VERIFIED', 'REJECTED', 'MISSING')")

    from sqlalchemy.dialects.postgresql import ENUM
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('document_type', ENUM('GST_CERTIFICATE', 'PAN_CARD', 'INCOME_TAX_RETURN', 'BANK_STATEMENT', name='documenttype', create_type=False), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requirements_id'), 'document_requirements', ['id'], unique=False)
    op.add_column('documents', sa.Column('status', ENUM('UPLOADED', 'VERIFIED', 'REJECTED', 'MISSING', name='documentstatus', create_type=False), nullable=True))
    op.add_column('documents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    
    # Cast existing document_type strings to the new ENUM
    op.execute("ALTER TABLE documents ALTER COLUMN document_type TYPE documenttype USING document_type::documenttype")
    
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(),
               type_=ENUM('GST_CERTIFICATE', 'PAN_CARD', 'INCOME_TAX_RETURN', 'BANK_STATEMENT', name='documenttype', create_type=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=sa.Enum('GST_CERTIFICATE', 'PAN_CARD', 'INCOME_TAX_RETURN', 'BANK_STATEMENT', name='documenttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('documents', 'verified_at')
    op.drop_column('documents', 'status')
    op.drop_index(op.f('ix_document_requirements_id'), table_name='document_requirements')
    op.drop_table('document_requirements')
    # ### end Alembic commands ###
